### ISSUE TITLE
Create tests for showing S-S dimer-dimer linkage can't form

### ISSUE THREAD

**Issue by michaelorella** [michaelorella/lignin-kmc#10]
For some reason, we are getting changes when we include the dimer,dimer energetics even though this shouldn't be allowed. Make sure that I create particular test cases that show this BO4 bond can't form.

**Comment by hmayes** [comment]
Do you want me to help with this? It I could add this pretty quickly....

**Comment by michaelorella** [comment]
If you want to add your own tests, that would be awesome! This was mostly just going to be for debugging as I get the new data tomorrow, so was hoping to get pretty fine with the tests.

**Comment by michaelorella** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create tests showing proper and improper event creation](https://trello.com/c/sKMFTYzX/1-create-tests-showing-proper-and-improper-event-creation)

**Comment by hmayes** [comment]
To clarify, do you mean S-S beta-O-4 dimer-dimer?

**Comment by hmayes** [comment]
FYI: see  " # todo: delete when questions re olig-olig b04 bond is resolved "
There is a temporary bit of code to help with this if you're still interesting in looking into this. If raises an error if an S-S olig-olig beta-o-4 bond forms.

My suspicion is that the hashing is what was causing unexpected behavior. You can test this by seeing how results change if you remove that bond type from the list now that the hashing is removed.

**Comment by hmayes** [comment]
I don't think this is necessary any longer.
