### ISSUE TITLE
Import error in create_lignin.py

### ISSUE THREAD

**Issue by runxuanjiang** [michaelorella/lignin-kmc#15]
Hi,

I just wanted to bring to your attention that the current version of lignin-kmc does not work with the latest version of the "common_wrangler" dependency.

Specifically this line here: https://github.com/michaelorella/lignin-kmc/blob/master/ligninkmc/create_lignin.py#L15
causes the error
```
ImportError: cannot import name 'H' from 'common_wrangler.common'
```

It appears that this is caused by a recent commit to the common_wrangler code: it seems they have renamed the `H` constant to `PLANCK_CONST_JS`: https://github.com/team-mayes/common_wrangler/commit/075c1ea2a129f97fe04211b938d761b1958bfd3f

**Comment by runxuanjiang** [comment]
Update: I've created a pull request (#16)  with some basic code that fixes this issue. Feel free to use it or discard it if you want to use an alternate solution.

**Comment by hmayes** [comment]
Great catch!
