### ISSUE TITLE
Mike to check on Fig 5 images

### ISSUE THREAD

**Issue by hmayes** [michaelorella/lignin-kmc#5]
Synchronous approaches:
1) Rerun the ipynbs used for manuscript

2) See if Heather's scripts help

**Comment by michaelorella** [comment]
I will be updating these comments as I continue to get data from rerunning the original notebooks. To start, the results from rerunning the notebooks exactly as is, is shown below.

![image](https://user-images.githubusercontent.com/40570716/70162078-1530b400-168b-11ea-8fb0-9259887b6ccd.png)

This data appears to match nearly exactly what was shown in the manuscript, a good sign! However, this doesn't appear to match what @hmayes was seeing when not including the extra S-S, dimer-dimer term. However, based on lignin chemistry, we wouldn't expect that these bonds should be able to form, and as such wouldn't expect any changes. I have added issue #10 to elucidate where any such issues might be occurring.

**Comment by hmayes** [comment]
Haha, hopefully I really did mix up the labels (the only thing that would
make sense of my slide). I'm curious to see the results when you rerun with
the additional term!
Thanks!
-Heather

**Comment by michaelorella** [comment]
Okay, so this is the result of running the notebooks with the additional term added. I've included screenshots of the cells, just to make sure that I didn't miss anything silly.

![image](https://user-images.githubusercontent.com/40570716/70249171-03621600-174a-11ea-9c10-81162a808aab.png)

![image](https://user-images.githubusercontent.com/40570716/70254983-fba76f00-1753-11ea-9a51-6de432aa9060.png)

![image](https://user-images.githubusercontent.com/40570716/70249547-84211200-174a-11ea-9848-53ead16bffc5.png)

![image](https://user-images.githubusercontent.com/40570716/70249594-969b4b80-174a-11ea-9d55-e5b65fafe303.png)

![image](https://user-images.githubusercontent.com/40570716/70249680-baf72800-174a-11ea-888d-0ef704ee4d8b.png)

Based on these, I'm a little confused about what changes what might have been made that could explain your slides... Like I said, I will take a look at adding some more detailed tests with specific chemistry that I know *should* and *shouldn't* occur.
